// Code generated by file2byteslice. DO NOT EDIT.

package resources

var ConfigJson = []byte("{\n  \"screenWidth\": 640,\n  \"screenHeight\": 480,\n  \"title\": \"外星人入侵\",\n  \"bgColor\": {\n    \"r\": 230,\n    \"g\": 230,\n    \"b\": 230,\n    \"a\": 255\n  },\n  \"shipSpeedFactor\": 3,\n  \"bulletWidth\": 3,\n  \"bulletHeight\": 15,\n  \"bulletSpeedFactor\": 2,\n  \"bulletColor\": {\n    \"r\": 80,\n    \"g\": 80,\n    \"b\": 80,\n    \"a\": 255\n  },\n  \"maxBulletNum\": 10,\n  \"bulletInterval\": 50,\n  \"alienSpeedFactor\": 2,\n  \"titleFontSize\": 12,\n  \"fontSize\": 10,\n  \"smallFontSize\": 6\n}")
