// Code generated by github.com/Karitham/handlergen. DO NOT EDIT.
package demo

import (
	"encoding/json"
	"github.com/Karitham/handlergen/gen"
	"github.com/go-chi/chi/v5"
	"net/http"
	"strconv"
)

type Handlers interface {
	example1(http.ResponseWriter, *http.Request, uint, gen.Template)
	example2(http.ResponseWriter, *http.Request, int, string, uint, int)
	example3(http.ResponseWriter, *http.Request, int, string, int, string, int)
}

func Example1(h Handlers) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		queryPage := query.Get("page")
		Page64, err := strconv.ParseUint(queryPage, 10, 64)
		if err != nil {
			http.Error(w, "invalid query", 400)
			return
		}
		Page := uint(Page64)

		var body gen.Template
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			http.Error(w, "invalid body", 400)
			return
		}

		h.example1(
			w,
			r,
			Page,
			body,
		)
	}
}

func Example2(h Handlers) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		queryPerPage := query.Get("per_page")
		PerPage, err := strconv.Atoi(queryPerPage)
		if err != nil {
			http.Error(w, "invalid query", 400)
			return
		}
		User := query.Get("user")
		queryUserId := query.Get("user_id")
		UserId64, err := strconv.ParseUint(queryUserId, 10, 64)
		if err != nil {
			http.Error(w, "invalid query", 400)
			return
		}
		UserId := uint(UserId64)
		queryPage := query.Get("page")
		Page, err := strconv.Atoi(queryPage)
		if err != nil {
			http.Error(w, "invalid query", 400)
			return
		}

		h.example2(
			w,
			r,
			PerPage,
			User,
			UserId,
			Page,
		)
	}
}

func Example3(h Handlers) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		queryPerPage := query.Get("per_page")
		PerPage, err := strconv.Atoi(queryPerPage)
		if err != nil {
			http.Error(w, "invalid query", 400)
			return
		}
		User := query.Get("user")
		queryPage := query.Get("page")
		Page, err := strconv.Atoi(queryPage)
		if err != nil {
			http.Error(w, "invalid query", 400)
			return
		}
		ApiToken := r.Header.Get("api_token")
		queryUserId := chi.URLParam(r, "user_id")
		UserId, err := strconv.Atoi(queryUserId)
		if err != nil {
			http.Error(w, "invalid query", 400)
			return
		}

		h.example3(
			w,
			r,
			PerPage,
			User,
			Page,
			ApiToken,
			UserId,
		)
	}
}
