// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlertAggrView = "alert_aggr_view"

// AlertAggrView mapped from table <alert_aggr_view>
type AlertAggrView struct {
	ID       int64  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	Name     string `gorm:"column:name;type:varchar(191);not null" json:"name"`
	Rule     string `gorm:"column:rule;type:varchar(2048);not null" json:"rule"`
	Cate     int64  `gorm:"column:cate;type:tinyint(1);not null;comment:0: preset 1: custom" json:"cate"`
	CreateAt int64  `gorm:"column:create_at;type:bigint(20);not null" json:"create_at"`
	CreateBy int64  `gorm:"column:create_by;type:bigint(20);not null;comment:user id" json:"create_by"`
	UpdateAt int64  `gorm:"column:update_at;type:bigint(20);not null" json:"update_at"`
}

// TableName AlertAggrView's table name
func (*AlertAggrView) TableName() string {
	return TableNameAlertAggrView
}
