// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlertSubscribe = "alert_subscribe"

// AlertSubscribe mapped from table <alert_subscribe>
type AlertSubscribe struct {
	ID               int64  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	Name             string `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Disabled         int64  `gorm:"column:disabled;type:tinyint(1);not null;comment:0:enabled 1:disabled" json:"disabled"`
	GroupID          int64  `gorm:"column:group_id;type:bigint(20);not null;comment:busi group id" json:"group_id"`
	Prod             string `gorm:"column:prod;type:varchar(255);not null" json:"prod"`
	Cate             string `gorm:"column:cate;type:varchar(128);not null" json:"cate"`
	DatasourceIds    string `gorm:"column:datasource_ids;type:varchar(255);not null;comment:datasource ids" json:"datasource_ids"`
	Cluster          string `gorm:"column:cluster;type:varchar(128);not null" json:"cluster"`
	RuleID           int64  `gorm:"column:rule_id;type:bigint(20);not null" json:"rule_id"`
	Tags             string `gorm:"column:tags;type:varchar(4096);not null;comment:json,map,tagkey->regexp|value" json:"tags"`
	RedefineSeverity int64  `gorm:"column:redefine_severity;type:tinyint(1);comment:is redefine severity?" json:"redefine_severity"`
	NewSeverity      int64  `gorm:"column:new_severity;type:tinyint(1);not null;comment:0:Emergency 1:Warning 2:Notice" json:"new_severity"`
	RedefineChannels int64  `gorm:"column:redefine_channels;type:tinyint(1);comment:is redefine channels?" json:"redefine_channels"`
	NewChannels      string `gorm:"column:new_channels;type:varchar(255);not null;comment:split by space: sms voice email dingtalk wecom" json:"new_channels"`
	UserGroupIds     string `gorm:"column:user_group_ids;type:varchar(250);not null;comment:split by space 1 34 5, notify cc to user_group_ids" json:"user_group_ids"`
	Webhooks         string `gorm:"column:webhooks;type:text;not null" json:"webhooks"`
	RedefineWebhooks int64  `gorm:"column:redefine_webhooks;type:tinyint(1)" json:"redefine_webhooks"`
	ForDuration      int64  `gorm:"column:for_duration;type:bigint(20);not null" json:"for_duration"`
	CreateAt         int64  `gorm:"column:create_at;type:bigint(20);not null" json:"create_at"`
	CreateBy         string `gorm:"column:create_by;type:varchar(64);not null" json:"create_by"`
	UpdateAt         int64  `gorm:"column:update_at;type:bigint(20);not null" json:"update_at"`
	UpdateBy         string `gorm:"column:update_by;type:varchar(64);not null" json:"update_by"`
}

// TableName AlertSubscribe's table name
func (*AlertSubscribe) TableName() string {
	return TableNameAlertSubscribe
}
