// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlertingEngine = "alerting_engines"

// AlertingEngine mapped from table <alerting_engines>
type AlertingEngine struct {
	ID           int64  `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	Instance     string `gorm:"column:instance;type:varchar(128);not null;comment:instance identification, e.g. 10.9.0.9:9090" json:"instance"`
	DatasourceID int64  `gorm:"column:datasource_id;type:bigint(20);not null;comment:datasource id" json:"datasource_id"`
	Cluster      string `gorm:"column:cluster;type:varchar(128);not null;comment:n9e-alert cluster" json:"cluster"`
	Clock        int64  `gorm:"column:clock;type:bigint(20);not null" json:"clock"`
}

// TableName AlertingEngine's table name
func (*AlertingEngine) TableName() string {
	return TableNameAlertingEngine
}
