// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlertMute = "alert_mute"

// AlertMute mapped from table <alert_mute>
type AlertMute struct {
	ID            int64  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	GroupID       int64  `gorm:"column:group_id;type:bigint(20);not null;comment:busi group id" json:"group_id"`
	Prod          string `gorm:"column:prod;type:varchar(255);not null" json:"prod"`
	Note          string `gorm:"column:note;type:varchar(1024);not null" json:"note"`
	Cate          string `gorm:"column:cate;type:varchar(128);not null" json:"cate"`
	Cluster       string `gorm:"column:cluster;type:varchar(128);not null" json:"cluster"`
	DatasourceIds string `gorm:"column:datasource_ids;type:varchar(255);not null;comment:datasource ids" json:"datasource_ids"`
	Tags          string `gorm:"column:tags;type:varchar(4096);not null;comment:json,map,tagkey->regexp|value" json:"tags"`
	Cause         string `gorm:"column:cause;type:varchar(255);not null" json:"cause"`
	Btime         int64  `gorm:"column:btime;type:bigint(20);not null;comment:begin time" json:"btime"`
	Etime         int64  `gorm:"column:etime;type:bigint(20);not null;comment:end time" json:"etime"`
	Disabled      int64  `gorm:"column:disabled;type:tinyint(1);not null;comment:0:enabled 1:disabled" json:"disabled"`
	MuteTimeType  int64  `gorm:"column:mute_time_type;type:tinyint(1);not null" json:"mute_time_type"`
	PeriodicMutes string `gorm:"column:periodic_mutes;type:varchar(4096);not null" json:"periodic_mutes"`
	CreateAt      int64  `gorm:"column:create_at;type:bigint(20);not null" json:"create_at"`
	CreateBy      string `gorm:"column:create_by;type:varchar(64);not null" json:"create_by"`
	UpdateAt      int64  `gorm:"column:update_at;type:bigint(20);not null" json:"update_at"`
	UpdateBy      string `gorm:"column:update_by;type:varchar(64);not null" json:"update_by"`
}

// TableName AlertMute's table name
func (*AlertMute) TableName() string {
	return TableNameAlertMute
}
