// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAppServer = "app_server"

// AppServer mapped from table <app_server>
type AppServer struct {
	ID          int64  `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键" json:"id,string"`
	Name        string `gorm:"column:name;type:varchar(120);not null;comment:主机名称" json:"name"`
	IP          string `gorm:"column:ip;type:varchar(64);not null;comment:主机域名或者IP" json:"ip"`
	InternalIP  string `gorm:"column:internal_ip;type:varchar(255);comment:内网地址" json:"internal_ip"`
	OsVersion   string `gorm:"column:os_version;type:varchar(255);comment:操作系统版本" json:"os_version"`
	CPUCnt      int64  `gorm:"column:cpu_cnt;type:int(11);comment:cpu 核数" json:"cpu_cnt"`
	Memory      string `gorm:"column:memory;type:varchar(64);comment:内存容量" json:"memory"`
	Disk        string `gorm:"column:disk;type:varchar(64);comment:硬盘容量" json:"disk"`
	Description string `gorm:"column:description;type:varchar(255);comment:主机说明,记录 cpu 内存 硬盘 网络的购买信息" json:"description"`
	CreateAt    int64  `gorm:"column:create_at;type:bigint(20);comment:创建时间" json:"create_at"`
	CreateBy    string `gorm:"column:create_by;type:varchar(255)" json:"create_by"`
	UpdateAt    int64  `gorm:"column:update_at;type:bigint(20);comment:更新时间" json:"update_at"`
	UpdateBy    string `gorm:"column:update_by;type:varchar(255)" json:"update_by"`
}

// TableName AppServer's table name
func (*AppServer) TableName() string {
	return TableNameAppServer
}
