// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBoard = "board"

// Board mapped from table <board>
type Board struct {
	ID       int64  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	GroupID  int64  `gorm:"column:group_id;type:bigint(20);not null;comment:busi group id" json:"group_id"`
	Name     string `gorm:"column:name;type:varchar(191);not null" json:"name"`
	Ident    string `gorm:"column:ident;type:varchar(200);not null" json:"ident"`
	Tags     string `gorm:"column:tags;type:varchar(255);not null;comment:split by space" json:"tags"`
	Public   int64  `gorm:"column:public;type:tinyint(1);not null;comment:0:false 1:true" json:"public"`
	BuiltIn  int64  `gorm:"column:built_in;type:tinyint(1);not null;comment:0:false 1:true" json:"built_in"`
	Hide     int64  `gorm:"column:hide;type:tinyint(1);not null;comment:0:false 1:true" json:"hide"`
	CreateAt int64  `gorm:"column:create_at;type:bigint(20);not null" json:"create_at"`
	CreateBy string `gorm:"column:create_by;type:varchar(64);not null" json:"create_by"`
	UpdateAt int64  `gorm:"column:update_at;type:bigint(20);not null" json:"update_at"`
	UpdateBy string `gorm:"column:update_by;type:varchar(64);not null" json:"update_by"`
}

// TableName Board's table name
func (*Board) TableName() string {
	return TableNameBoard
}
