// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBoardPayload = "board_payload"

// BoardPayload mapped from table <board_payload>
type BoardPayload struct {
	ID      int64  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;comment:dashboard id" json:"id,string"`
	Payload string `gorm:"column:payload;type:mediumtext;not null" json:"payload"`
}

// TableName BoardPayload's table name
func (*BoardPayload) TableName() string {
	return TableNameBoardPayload
}
