// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBuiltinCate = "builtin_cate"

// BuiltinCate mapped from table <builtin_cate>
type BuiltinCate struct {
	ID     int64  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	Name   string `gorm:"column:name;type:varchar(191);not null" json:"name"`
	UserID int64  `gorm:"column:user_id;type:bigint(20);not null" json:"user_id"`
}

// TableName BuiltinCate's table name
func (*BuiltinCate) TableName() string {
	return TableNameBuiltinCate
}
