// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBusiGroupMember = "busi_group_member"

// BusiGroupMember mapped from table <busi_group_member>
type BusiGroupMember struct {
	ID          int64  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	BusiGroupID int64  `gorm:"column:busi_group_id;type:bigint(20);not null;comment:busi group id" json:"busi_group_id"`
	UserGroupID int64  `gorm:"column:user_group_id;type:bigint(20);not null;comment:user group id" json:"user_group_id"`
	PermFlag    string `gorm:"column:perm_flag;type:char(2);not null;comment:ro | rw" json:"perm_flag"`
}

// TableName BusiGroupMember's table name
func (*BusiGroupMember) TableName() string {
	return TableNameBusiGroupMember
}
