// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChartShare = "chart_share"

// ChartShare mapped from table <chart_share>
type ChartShare struct {
	ID           int64  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	Cluster      string `gorm:"column:cluster;type:varchar(128);not null" json:"cluster"`
	DashboardID  int64  `gorm:"column:dashboard_id;type:bigint(20) unsigned;not null" json:"dashboard_id"`
	DatasourceID int64  `gorm:"column:datasource_id;type:bigint(20) unsigned;not null" json:"datasource_id"`
	Configs      string `gorm:"column:configs;type:text" json:"configs"`
	CreateAt     int64  `gorm:"column:create_at;type:bigint(20);not null" json:"create_at"`
	CreateBy     string `gorm:"column:create_by;type:varchar(64);not null" json:"create_by"`
}

// TableName ChartShare's table name
func (*ChartShare) TableName() string {
	return TableNameChartShare
}
