// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChartGroup = "chart_group"

// ChartGroup mapped from table <chart_group>
type ChartGroup struct {
	ID          int64  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	DashboardID int64  `gorm:"column:dashboard_id;type:bigint(20) unsigned;not null" json:"dashboard_id"`
	Name        string `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Weight      int64  `gorm:"column:weight;type:int(11);not null" json:"weight"`
}

// TableName ChartGroup's table name
func (*ChartGroup) TableName() string {
	return TableNameChartGroup
}
