// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChart = "chart"

// Chart mapped from table <chart>
type Chart struct {
	ID      int64  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	GroupID int64  `gorm:"column:group_id;type:bigint(20) unsigned;not null;comment:chart group id" json:"group_id"`
	Configs string `gorm:"column:configs;type:text" json:"configs"`
	Weight  int64  `gorm:"column:weight;type:int(11);not null" json:"weight"`
}

// TableName Chart's table name
func (*Chart) TableName() string {
	return TableNameChart
}
