// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameConfig = "configs"

// Config mapped from table <configs>
type Config struct {
	ID   int64  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	Ckey string `gorm:"column:ckey;type:varchar(191);not null" json:"ckey"`
	Cval string `gorm:"column:cval;type:varchar(4096);not null" json:"cval"`
}

// TableName Config's table name
func (*Config) TableName() string {
	return TableNameConfig
}
