// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDatasource = "datasource"

// Datasource mapped from table <datasource>
type Datasource struct {
	ID             int64  `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	Name           string `gorm:"column:name;type:varchar(191);not null" json:"name"`
	Description    string `gorm:"column:description;type:varchar(255);not null" json:"description"`
	Category       string `gorm:"column:category;type:varchar(255);not null" json:"category"`
	PluginID       int64  `gorm:"column:plugin_id;type:int(10) unsigned;not null" json:"plugin_id"`
	PluginType     string `gorm:"column:plugin_type;type:varchar(255);not null" json:"plugin_type"`
	PluginTypeName string `gorm:"column:plugin_type_name;type:varchar(255);not null" json:"plugin_type_name"`
	ClusterName    string `gorm:"column:cluster_name;type:varchar(255);not null" json:"cluster_name"`
	Settings       string `gorm:"column:settings;type:text;not null" json:"settings"`
	Status         string `gorm:"column:status;type:varchar(255);not null" json:"status"`
	HTTP           string `gorm:"column:http;type:varchar(4096);not null" json:"http"`
	Auth           string `gorm:"column:auth;type:varchar(8192);not null" json:"auth"`
	CreatedAt      int64  `gorm:"column:created_at;type:bigint(20);not null" json:"created_at"`
	CreatedBy      string `gorm:"column:created_by;type:varchar(64);not null" json:"created_by"`
	UpdatedAt      int64  `gorm:"column:updated_at;type:bigint(20);not null" json:"updated_at"`
	UpdatedBy      string `gorm:"column:updated_by;type:varchar(64);not null" json:"updated_by"`
}

// TableName Datasource's table name
func (*Datasource) TableName() string {
	return TableNameDatasource
}
