// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTaskRecord = "task_record"

// TaskRecord mapped from table <task_record>
type TaskRecord struct {
	ID           int64  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;comment:ibex task id" json:"id,string"`
	GroupID      int64  `gorm:"column:group_id;type:bigint(20);not null;comment:busi group id" json:"group_id"`
	IbexAddress  string `gorm:"column:ibex_address;type:varchar(128);not null" json:"ibex_address"`
	IbexAuthUser string `gorm:"column:ibex_auth_user;type:varchar(128);not null" json:"ibex_auth_user"`
	IbexAuthPass string `gorm:"column:ibex_auth_pass;type:varchar(128);not null" json:"ibex_auth_pass"`
	Title        string `gorm:"column:title;type:varchar(255);not null" json:"title"`
	Account      string `gorm:"column:account;type:varchar(64);not null" json:"account"`
	Batch        int64  `gorm:"column:batch;type:int(10) unsigned;not null" json:"batch"`
	Tolerance    int64  `gorm:"column:tolerance;type:int(10) unsigned;not null" json:"tolerance"`
	Timeout      int64  `gorm:"column:timeout;type:int(10) unsigned;not null" json:"timeout"`
	Pause        string `gorm:"column:pause;type:varchar(255);not null" json:"pause"`
	Script       string `gorm:"column:script;type:text;not null" json:"script"`
	Args         string `gorm:"column:args;type:varchar(512);not null" json:"args"`
	CreateAt     int64  `gorm:"column:create_at;type:bigint(20);not null" json:"create_at"`
	CreateBy     string `gorm:"column:create_by;type:varchar(64);not null" json:"create_by"`
}

// TableName TaskRecord's table name
func (*TaskRecord) TableName() string {
	return TableNameTaskRecord
}
