// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTaskTpl = "task_tpl"

// TaskTpl mapped from table <task_tpl>
type TaskTpl struct {
	ID        int64  `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	GroupID   int64  `gorm:"column:group_id;type:int(10) unsigned;not null;comment:busi group id" json:"group_id"`
	Title     string `gorm:"column:title;type:varchar(255);not null" json:"title"`
	Account   string `gorm:"column:account;type:varchar(64);not null" json:"account"`
	Batch     int64  `gorm:"column:batch;type:int(10) unsigned;not null" json:"batch"`
	Tolerance int64  `gorm:"column:tolerance;type:int(10) unsigned;not null" json:"tolerance"`
	Timeout   int64  `gorm:"column:timeout;type:int(10) unsigned;not null" json:"timeout"`
	Pause     string `gorm:"column:pause;type:varchar(255);not null" json:"pause"`
	Script    string `gorm:"column:script;type:text;not null" json:"script"`
	Args      string `gorm:"column:args;type:varchar(512);not null" json:"args"`
	Tags      string `gorm:"column:tags;type:varchar(255);not null;comment:split by space" json:"tags"`
	CreateAt  int64  `gorm:"column:create_at;type:bigint(20);not null" json:"create_at"`
	CreateBy  string `gorm:"column:create_by;type:varchar(64);not null" json:"create_by"`
	UpdateAt  int64  `gorm:"column:update_at;type:bigint(20);not null" json:"update_at"`
	UpdateBy  string `gorm:"column:update_by;type:varchar(64);not null" json:"update_by"`
}

// TableName TaskTpl's table name
func (*TaskTpl) TableName() string {
	return TableNameTaskTpl
}
