// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package tutorial

import (
	"database/sql"
)

type Author struct {
	// 自增ID
	ID int64
	// 作者名字
	Name string
	// 作者昵称
	NickName string
	// 创建时间
	CreatedAt sql.NullTime
	// 最后更新时间
	UpdatedAt sql.NullTime
}

type AuthorArticle struct {
	// 自增ID
	ID int64
	// 作者id
	AuthorID       int64
	ArticleContent string
	// 创建时间
	CreatedAt sql.NullTime
	// 最后更新时间
	UpdatedAt sql.NullTime
}
