// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package tutorial

import (
	"context"
	"database/sql"
)

const createAuthor = `-- name: CreateAuthor :execresult
INSERT INTO authors (name, nick_name)
VALUES (?, ?)
`

type CreateAuthorParams struct {
	Name     string
	NickName string
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAuthor, arg.Name, arg.NickName)
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE
FROM authors
WHERE id = ?
`

func (q *Queries) DeleteAuthor(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAuthor, id)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, nick_name, created_at, updated_at
FROM authors
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAuthor(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NickName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthorArticles = `-- name: GetAuthorArticles :many
SELECT id, author_id, article_content, created_at, updated_at
FROM author_articles
WHERE author_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetAuthorArticles(ctx context.Context, authorID int64) ([]AuthorArticle, error) {
	rows, err := q.db.QueryContext(ctx, getAuthorArticles, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorArticle
	for rows.Next() {
		var i AuthorArticle
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.ArticleContent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, nick_name, created_at, updated_at
FROM authors
ORDER BY name
`

func (q *Queries) ListAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NickName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
