// Code generated by "stringer -linecomment -type ErrCode ./mycodes"; DO NOT EDIT.

package mycodes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SUCCESS-200]
	_ = x[BadRequest-400]
	_ = x[Unauthorized-401]
	_ = x[Forbidden-403]
	_ = x[TooManyRequest-429]
	_ = x[InternalServer-500]
	_ = x[UsernameOrPassword-10001]
	_ = x[UserClosed-10002]
	_ = x[NoRegister-10003]
	_ = x[PhoneExist-10004]
	_ = x[VerifyCodeExpired-10005]
	_ = x[ErrorVerifyCode-10006]
	_ = x[VerifyCodeHasUsed-10007]
	_ = x[ErrorSaveAvatar-10008]
	_ = x[ErrorConversationReachedTrialLimit-10009]
	_ = x[ErrorPlaceOrder-10010]
	_ = x[ErrorNotifyOrder-10011]
	_ = x[ErrorContentIllegal-10012]
	_ = x[ErrorGPT4ConversationReachedDailyLimit-10013]
	_ = x[ErrorNotVipGPT4ConversationNotAllowed-10014]
	_ = x[ErrorCreditReachedLimit-10015]
	_ = x[ErrorNotAllowedEngine-10016]
}

const (
	_ErrCode_name_0 = "SUCCESS"
	_ErrCode_name_1 = "BadRequestUnauthorized"
	_ErrCode_name_2 = "Forbidden"
	_ErrCode_name_3 = "TooManyRequest"
	_ErrCode_name_4 = "InternalServer"
	_ErrCode_name_5 = "用户名或密码不正确用户被禁用了用户还没有注册手机号已经存在验证码超过有效期验证码错误验证码已使用保存头像出错达到会话数量限制订单创建失败订单创建失败内容非法达到gpt4会话每日数量限制非会员禁止发起gpt4会话剩余字符不足非vip用户禁止试用引擎"
)

var (
	_ErrCode_index_1 = [...]uint8{0, 10, 22}
	_ErrCode_index_5 = [...]uint16{0, 27, 45, 66, 87, 111, 126, 144, 162, 186, 204, 222, 234, 268, 299, 317, 347}
)

func (i ErrCode) String() string {
	switch {
	case i == 200:
		return _ErrCode_name_0
	case 400 <= i && i <= 401:
		i -= 400
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	case i == 403:
		return _ErrCode_name_2
	case i == 429:
		return _ErrCode_name_3
	case i == 500:
		return _ErrCode_name_4
	case 10001 <= i && i <= 10016:
		i -= 10001
		return _ErrCode_name_5[_ErrCode_index_5[i]:_ErrCode_index_5[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
